"""added tables for suit

Revision ID: 1471556eb034
Revises: 51d20fa24f89
Create Date: 2026-04-09 01:15:58.263347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1471556eb034'
down_revision: Union[str, Sequence[str], None] = '51d20fa24f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suit_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('suit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suit_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suit_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['suit_color.id'], ),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suit_id', 'color_id', name='uq_suit_file_suit_color')
    )
    op.add_column('generation', sa.Column('suit_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation', 'suit_file', ['suit_file_id'], ['id'])
    op.add_column('user', sa.Column('suit_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'suit_file', ['suit_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'suit_file_id')
    op.drop_constraint(None, 'generation', type_='foreignkey')
    op.drop_column('generation', 'suit_file_id')
    op.drop_table('suit_file')
    op.drop_table('suit_color')
    op.drop_table('suit')
    # ### end Alembic commands ###
