"""added boots tables

Revision ID: 51d20fa24f89
Revises: f4fa1541d494
Create Date: 2026-04-08 03:09:20.500032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d20fa24f89'
down_revision: Union[str, Sequence[str], None] = 'f4fa1541d494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boot_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('boot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boot_id'], ['boot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boot_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boot_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['boot_id'], ['boot.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['boot_color.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boot_id', 'color_id', name='uq_boot_file_boot_color')
    )
    op.add_column('generation', sa.Column('boot_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation', 'boot_file', ['boot_file_id'], ['id'])
    op.add_column('user', sa.Column('boot_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'boot_file', ['boot_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'boot_file_id')
    op.drop_constraint(None, 'generation', type_='foreignkey')
    op.drop_column('generation', 'boot_file_id')
    op.drop_table('boot_file')
    op.drop_table('boot_color')
    op.drop_table('boot')
    # ### end Alembic commands ###
