"""add jackets

Revision ID: 5bfe27be8b2a
Revises: ce72b6cf8a1e
Create Date: 2026-04-03 04:55:34.562557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfe27be8b2a'
down_revision: Union[str, Sequence[str], None] = 'ce72b6cf8a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jacket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jacket_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('jacket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jacket_id'], ['jacket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jacket_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jacket_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['jacket_color.id'], ),
    sa.ForeignKeyConstraint(['jacket_id'], ['jacket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jacket_id', 'color_id', name='uq_jacket_file_jacket_color')
    )
    op.add_column('generation', sa.Column('jacket_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation', 'jacket_file', ['jacket_file_id'], ['id'])
    op.add_column('user', sa.Column('jacket_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'jacket_file', ['jacket_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'jacket_file_id')
    op.drop_constraint(None, 'generation', type_='foreignkey')
    op.drop_column('generation', 'jacket_file_id')
    op.drop_table('jacket_file')
    op.drop_table('jacket_color')
    op.drop_table('jacket')
    # ### end Alembic commands ###
