"""added the final balance field to the user table

Revision ID: 72819409910b
Revises: 8d49c607926e
Create Date: 2026-04-10 15:52:15.803708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72819409910b'
down_revision: Union[str, Sequence[str], None] = '8d49c607926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
