"""modifed tables for location changing

Revision ID: 932de4fc46cb
Revises: 1471556eb034
Create Date: 2026-04-10 04:30:25.320209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932de4fc46cb'
down_revision: Union[str, Sequence[str], None] = '1471556eb034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'location_id')
    op.drop_column('location', 'description')
    # ### end Alembic commands ###
