"""add collages table

Revision ID: b987dcebd30e
Revises: 5bfe27be8b2a
Create Date: 2026-04-04 20:27:33.472868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b987dcebd30e'
down_revision: Union[str, Sequence[str], None] = '5bfe27be8b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('models_count', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'brand', name='uq_collage_type_brand')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collage')
    # ### end Alembic commands ###
