"""added gloves tables

Revision ID: c548331a69fe
Revises: b987dcebd30e
Create Date: 2026-04-04 22:35:07.159731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c548331a69fe'
down_revision: Union[str, Sequence[str], None] = 'b987dcebd30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glove',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glove_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('glove_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glove_id'], ['glove.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glove_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glove_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['glove_color.id'], ),
    sa.ForeignKeyConstraint(['glove_id'], ['glove.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('glove_id', 'color_id', name='uq_glove_file_glove_color')
    )
    op.add_column('generation', sa.Column('glove_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation', 'glove_file', ['glove_file_id'], ['id'])
    op.add_column('user', sa.Column('glove_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'glove_file', ['glove_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'glove_file_id')
    op.drop_constraint(None, 'generation', type_='foreignkey')
    op.drop_column('generation', 'glove_file_id')
    op.drop_table('glove_file')
    op.drop_table('glove_color')
    op.drop_table('glove')
    # ### end Alembic commands ###
