"""add email to account

Revision ID: ce72b6cf8a1e
Revises: ab829c86af22
Create Date: 2026-04-02 02:11:06.805311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce72b6cf8a1e'
down_revision: Union[str, Sequence[str], None] = 'ab829c86af22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'email')
    # ### end Alembic commands ###
