"""modified collage table

Revision ID: f4fa1541d494
Revises: c548331a69fe
Create Date: 2026-04-07 04:01:06.117896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fa1541d494'
down_revision: Union[str, Sequence[str], None] = 'c548331a69fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collage', sa.Column('model_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_collage_type_brand'), 'collage', type_='unique')
    op.create_unique_constraint('uq_collage_type_brand_model', 'collage', ['type', 'brand', 'model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_collage_type_brand_model', 'collage', type_='unique')
    op.create_unique_constraint(op.f('uq_collage_type_brand'), 'collage', ['type', 'brand'], postgresql_nulls_not_distinct=False)
    op.drop_column('collage', 'model_id')
    # ### end Alembic commands ###
